In [2]:
!pip install xgboost

   ---------------------------------------- 0.0/150.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/150.0 MB ? eta -:--:--
   ---------------------------------------- 0.5/150.0 MB 2.4 MB/s eta 0:01:03
   ---------------------------------------- 1.0/150.0 MB 2.5 MB/s eta 0:01:00
   ---------------------------------------- 1.6/150.0 MB 2.5 MB/s eta 0:00:59
    --------------------------------------- 2.1/150.0 MB 2.9 MB/s eta 0:00:51
    --------------------------------------- 2.9/150.0 MB 2.8 MB/s eta 0:00:52
    --------------------------------------- 3.4/150.0 MB 2.8 MB/s eta 0:00:54
   - -------------------------------------- 4.5/150.0 MB 3.1 MB/s eta 0:00:47
   - -------------------------------------- 6.3/150.0 MB 3.8 MB/s eta 0:00:38
   -- ------------------------------------- 9.4/150.0 MB 5.1 MB/s eta 0:00:28
   --- ------------------------------------ 13.9/150.0 MB 6.8 MB/s eta 0:00:20
   ---- ----------------------------------- 16.8/150.0 MB 7.8 MB/s eta 0:00:1

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
import xgboost as xgb



Load the Data

In [6]:
df=pd.read_csv("heart (1).csv")
x=df.drop("target",axis=1)
y=df["target"]

Split Data

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

Scale features

In [8]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)


Models to compare

In [9]:
models = {
    "Logistic Regression": LogisticRegression(),
    "Random Forest": RandomForestClassifier(),
    "KNN": KNeighborsClassifier(),
    "SVM": SVC(),
    "Neural Network": MLPClassifier(max_iter=500),
    "XGBoost": xgb.XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}


Train and evaluate each model

In [12]:
for name, model in models.items():
    model.fit(x_train_scaled, y_train)
    y_pred = model.predict(x_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    print(f"\n{name} Accuracy: {acc:.2f}")
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test,y_pred))


Logistic Regression Accuracy: 0.80
[[73 27]
 [13 92]]
              precision    recall  f1-score   support

           0       0.85      0.73      0.78       100
           1       0.77      0.88      0.82       105

    accuracy                           0.80       205
   macro avg       0.81      0.80      0.80       205
weighted avg       0.81      0.80      0.80       205


Random Forest Accuracy: 1.00
[[100   0]
 [  0 105]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       100
           1       1.00      1.00      1.00       105

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205


KNN Accuracy: 0.86
[[90 10]
 [19 86]]
              precision    recall  f1-score   support

           0       0.83      0.90      0.86       100
           1       0.90      0.82      0.86       105

    accuracy                       

c:\Users\MAHIMA\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\MAHIMA\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [04:33:05] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)



Neural Network Accuracy: 1.00
[[100   0]
 [  0 105]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       100
           1       1.00      1.00      1.00       105

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205


XGBoost Accuracy: 1.00
[[100   0]
 [  0 105]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       100
           1       1.00      1.00      1.00       105

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205

